### PR TITLE
Update tracing with the last version of lwt (2.5.2)

### PR DESCRIPTION
**Pull request by dinosaure**
Conflicts:
- tests/META
- src/core/META
- myocamlbuild.ml
- setup.ml
- _tags

### CODE REVIEW

**Comment by samoht** [comment]
Would it be possible to rebase the existing tracing patches on top of lwt 2.5.2 instead?

**Comment by dinosaure** [comment]
@aantron @drup ?

**Comment by talex5** [comment]
A merge would be fine. But yes, the Git history needs to show the 2.5.2 commit that this is based on in the commit's parent field. Otherwise, future updates will become very difficult.

**Comment by aantron** [comment]
Hi @dinosaure, can the Lwt side be of help?

**Comment by talex5** [comment]
@aantron I think ideally Lwt would provide a tracing module with just null-ops in it, use that in `lwt.ml`, and let the compiler optimise the calls out. Then the tracing patch could just replace the tracing module with its own version.

Currently, there are quite a few changes to lwt.ml. It would be good to split these out and upstream the ones that make sense, although it's a fair bit of work:

https://github.com/ocsigen/lwt/compare/master...mirage:tracing#diff-94d283dcf718f431e5e0c2fc228c84bcR41

**Comment by aantron** [comment]
That seems plausible, without getting into the details. In any case, dealing with this "somehow" is now definitely on my to-do list, with https://github.com/ocsigen/lwt/issues/180 in mind.

**Comment by talex5** [comment]
Closing, as #11 updated to 2.6.

**Pull request closed without merging**
